### ISSUE TITLE
NOT-PARTICIPATING Showing on Hacktoberfest website

### ISSUE THREAD

**Issue by pradeep8577** [extinctsion/Hacktoberfest2023#4]

**Comment by extinctsion** [comment]
Pls take a sceen shot and show it here.

**Comment by pradeep8577** [comment]
[image: Hack.png]

**Comment by pradeep8577** [comment]
![Hack](https://github.com/extinctsion/Hacktoberfest2023/assets/72540482/f1881a55-ea3f-4fdd-8c1a-b941b7b3cfcc)

**Comment by extinctsion** [comment]
there has been an error in tag, its now fixed. try again. thank you
