### ISSUE TITLE
Resolve Bugs in Java Programs

### ISSUE THREAD

**Issue by Divyanshi014** [extinctsion/Hacktoberfest2023#58]
I can resolve Alternativepositiveandnegativenumbers, Palindrome and Commonelements bugs in Java Programs.

**Comment by extinctsion** [comment]
can you state the bugs here. Everyone would like to know the bugs

**Comment by Divyanshi014** [comment]
BUG1:
![image](https://github.com/extinctsion/Hacktoberfest2023/assets/104729988/95c417ce-1487-409c-85f8-f25cf83f9e14)
The calling of the rearrange method that does not exist, the public method syntax is wrong.                                                                    
BUG2:
![image](https://github.com/extinctsion/Hacktoberfest2023/assets/104729988/65568ae6-e7db-45d2-b16d-56c4dfa9d9ca)
 the  Palindrome class closing bracket is in the wrong place                                                                                                                       BUG3:
![image](https://github.com/extinctsion/Hacktoberfest2023/assets/104729988/00ecf113-5ee0-4a53-99d9-f011af16de1f)
the code here is not enclosed in any method

**Comment by Divyanshi014** [comment]
@extinctsion Kindly assign me to solve these bugs

**Comment by extinctsion** [comment]
ok

**Comment by Sajjad01-chaus** [comment]
i can solve the palindrome question easily by finding issuein it or by another method

**Comment by extinctsion** [comment]
I think this issue is now resolved. Hence, I'm closing this issue.
